//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMAN2013
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPMAN2013Entities : DbContext
    {
        public IPMAN2013Entities()
            : base("name=IPMAN2013Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableGroup> TableGroup { get; set; }
        public virtual DbSet<TableRequest> TableRequest { get; set; }
        public virtual DbSet<TableServer> TableServer { get; set; }
        public virtual DbSet<TableSession> TableSession { get; set; }
        public virtual DbSet<TableSubnet> TableSubnet { get; set; }
        public virtual DbSet<TableUser> TableUser { get; set; }
    }
}
